### ISSUE TITLE
Tx to library format 📝 

### ISSUE THREAD

**Issue by onmax** [alastria/alastria-identity-lib#131]
# Introduction
As we discussed in [this issue](https://github.com/alastria/alastria-identity-lib/issues/125), we are changing the format of the repo with three different libraries which will be uploaded to `npm` and `yarn`.

# Work to be done
Reorganize all files already created with the new structure explained [here](https://github.com/alastria/alastria-identity-lib/issues/125) and prepare the folder `tx-factory` in order to create a library.

## Tasks
- [ ] Move src files
- [ ] Create types
- [ ] Move tests
- [ ] Create its own package
- [ ] Test that the build works and save it as a JS in a folder called `dist`. This should be in .gitignore and therefore not uploaded.
- [ ] Create a tsconfig.json
- [ ] Create a README with basic explanation on how to use it
- [ ] Create a LICENSE file (?)
- [ ] Edit and create a new PR in the examples repository testing the new change using the library format

**Comment by VictorNS69** [comment]
We already have a LIECENSE file https://github.com/alastria/alastria-identity-lib/blob/master/LICENSE. Use it in every directory
